# Generated by Django 5.2.7 on 2025-11-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_employeeprofile_rating_employeereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
