# Generated by Django 5.2.7 on 2025-11-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='professional',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='professional',
            new_name='employee',
        ),
    ]
