# Generated by Django 5.2.7 on 2025-11-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_professional_booking_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='client',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
