# Generated by Django 5.2.7 on 2025-11-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('in_Progress', 'In_Progress'), ('completed', 'Completed'), ('incompleted', 'Incompleted')], default='pending', max_length=20),
        ),
    ]
